#!/bin/bash
echo "Applyng dotfiles backup"
cp -r ~/.config/alacritty ~/.git/dotfiles/.config
cp -r ~/.config/sway ~/.git/dotfiles/.config
cp -r ~/.config/swaylock ~/.git/dotfiles/.config
cp -r ~/.config/waybar ~/.git/dotfiles/.config
cp -r ~/.config/mako ~/.git/dotfiles/.config
cp -r ~/.config/ranger ~/.git/dotfiles/.config
cp -r ~/.config/scripts ~/.git/dotfiles/.config
cp -r ~/.config/gtk-3.0 ~/.git/dotfiles/.config
cp -r ~/.config/gtk-4.0 ~/.git/dotfiles/.config
cp ~/.nanorc ~/.git/dotfiles
cp ~/.zshrc ~/.git/dotfiles/
echo "Success!"
