#!/bin/bash

pacman -S sudo zsh zsh-autosuggestions zsh-syntax-highlighting exa git xorg xorg-xinit arandr bspwm sxhkd alacritty picom ranger rofi flameshot thunar thunar-volman thunar-archive-plugin thunar-media-tags-plugin gvfs file-roller firefox dunst parole gst-libav gst-plugins-bad gst-plugins-ugly transmission-gtk ristretto lxappearance nitrogen pulseaudio pavucontrol pamixer playerctl xdg-user-dirs nano-syntax-highlighting gnome-disk-utility ntfs-3g xfce4-power-manager --needed base-devel
