#! /bin/sh

#    ____ ____  ______        ____  __ 
#   | __ ) ___||  _ \ \      / /  \/  |
#   |  _ \___ \| |_) \ \ /\ / /| |\/| |
#   | |_) |__) |  __/ \ V  V / | |  | |
#   |____/____/|_|     \_/\_/  |_|  |_|

pgrep -x sxhkd > /dev/null || sxhkd &

MONITOR_NAME="eDP-1"
EXTERNAL_MONITOR_NAME="HDMI-1"

STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
    xrandr --output $MONITOR_NAME --primary --mode 1920x1080  --output $EXTERNAL_MONITOR_NAME --mode 1920x1080 --rotate normal --right-of $MONITOR_NAME
else
    xrandr --output $EXTERNAL_MONITOR_NAME --off
fi

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	bspc monitor $MONITOR_NAME -d 1 2 3
	bspc monitor $EXTERNAL_MONITOR_NAME -d 4 5
else
	bspc monitor -d 1 2 3 4 5
fi

bspc config focused_border_color     '#888E96'
bspc config normal_border_color      '#262626'

bspc config top_padding 	  2
bspc config left_padding 	  1
bspc config right_padding 	  1
bspc config border_width          0
bspc config window_gap           10
bspc config split_ratio          0.5

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Arandr state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Gnome-disks state=floating

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	$HOME/.config/polybar/launch2.sh
else
	$HOME/.config/polybar/launch.sh
fi

picom &

nitrogen --restore &

xfce4-power-manager &

nm-applet &

blueman-applet &

setxkbmap -model abnt2 -layout br -variant abnt2

xsetroot -cursor_name left_ptr
