shell=/usr/bin/zsh

font=JetBrainsMono Nerd Font:size=18

[colors]
alpha=1.0
foreground=E8E3E3
background=000000

# Normal/regular colors (color palette 0-7)
regular0=353535  # black
regular1=AC4142  # red
regular2=90A959  # green
regular3=f4bf75  # yellow
regular4=6a9fb5  # blue
regular5=aa759f  # magenta
regular6=75b5aa  # cyan
regular7=d0d0d0  # white

# Bright colors (color palette 8-15)
bright0=353535   # bright black
bright1=ac4142   # bright red
bright2=90a959   # bright green
bright3=f4bf75   # bright yellow
bright4=6a9fb5   # bright blue
bright5=aa759f   # bright magenta
bright6=75b5aa   # bright cyan
bright7=d0d0d0   # bright white
