#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

MONITOR_NAME="eDP1"
EXTERNAL_MONITOR_NAME="HDMI1"

STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
    xrandr --output $MONITOR_NAME --primary --mode 1920x1080  --output $EXTERNAL_MONITOR_NAME --mode 1920x1080 --rotate normal --right-of $MONITOR_NAME
else
    xrandr --output $EXTERNAL_MONITOR_NAME --off
fi

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	bspc monitor $MONITOR_NAME -d 1 2 3 4 5
	bspc monitor $EXTERNAL_MONITOR_NAME -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5
fi

bspc config border_width          0
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color     '#f0544c'
bspc config normal_border_color      '#888E96'

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	$HOME/.config/polybar/launch2.sh
else
	$HOME/.config/polybar/launch.sh
fi

xfce4-power-manager &

feh --bg-scale ${HOME}/Pictures/001.jpg

setxkbmap -model abnt2 -layout br -variant abnt2

xsetroot -cursor_name left_ptr

optimus-manager-qt &

nm-applet &

blueman-applet &

flameshot &
