#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI1 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color '#8be9fd'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Load Polybar
${HOME}/.config/polybar/launch.sh

#Set Wallpaper
feh --bg-scale ${HOME}/Pictures/001.png

#Set br-abnt2 Layout
setxkbmap -model abnt2 -layout br -variant abnt2

#Set Cursor in X
xsetroot -xcf /usr/share/icons/Volantes/cursors/left_ptr 24 &

#HDMI1
xrandr --output HDMI1 --primary
xrandr --output eDP1 --off

#eDP1
#xrandr --output eDP1 --primary
#xrandr --output HDMI1 --off
