#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5

bspc monitor HDMI1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color '#F0544C'
bspc config normal_border_color '#76797F'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.scripts/bspwm-dual-monitor ];then
    bspwm-dual-monitor
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/share/doc/polybar ]; then
    bash $HOME/.config/polybar/launch.sh
fi

#Load Polybar
#${HOME}/.config/polybar/launch.sh

#Set Wallpaper
feh --bg-scale ${HOME}/Pictures/001.jpg

#Set br-abnt2 Layout
setxkbmap -model abnt2 -layout br -variant abnt2

#Set Cursor in X
xsetroot -cursor_name left_ptr

#Exec network-manager-applet
nm-applet &

#Exec flameshot applet
flameshot &
