#!/bin/bash
echo "Applyng dotfiles backup"
cp -r ~/.config/alacritty ~/.git/dotfiles
cp -r ~/.config/foot ~/.git/dotfiles
cp -r ~/.config/sway ~/.git/dotfiles
cp -r ~/.config/swaylock ~/.git/dotfiles
cp -r ~/.config/waybar ~/.git/dotfiles
cp -r ~/.config/mako ~/.git/dotfiles/
cp -r ~/.config/wofi ~/.git/dotfiles/
cp -r ~/.config/ranger ~/.git/dotfiles/
cp -r ~/.config/zathura/ ~/.git/dotfiles/
cp -r ~/.config/scripts ~/.git/dotfiles
cp ~/.config/qutebrowser/config.py ~/.git/dotfiles/qutebrowser/
cp ~/.zshrc ~/.git/dotfiles
echo "Success!"
