#!/bin/bash
echo "Applyng dotfiles backup"
cp -r ~/.config/alacritty ~/.git/dotfiles
cp -r ~/.config/foot ~/.git/dotfiles
cp -r ~/.config/sway ~/.git/dotfiles
cp -r ~/.config/swaylock ~/.git/dotfiles
cp -r ~/.config/waybar ~/.git/dotfiles
cp -r ~/.config/mako ~/.git/dotfiles/
cp -r ~/.config/ranger ~/.git/dotfiles/
cp -r ~/.config/zathura/ ~/.git/dotfiles/
cp ~/.config/lvim/config.lua ~/.git/dotfiles/lvim
cp -r ~/.config/scripts ~/.git/dotfiles
cp ~/.config/mpd/mpd.conf ~/.git/dotfiles/mpd/
cp ~/.config/mpd/database ~/.git/dotfiles/mpd/
cp ~/.ncmpcpp/config ~/.git/dotfiles/.ncmpcpp/
cp ~/.zshrc ~/.git/dotfiles
echo "Success!"
