set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Adwaita dark theme colors
thm_bg="#272727"
thm_fg="#d0d0d0"
thm_cyan="#75b5aa"
thm_black="#151515"
thm_gray="#353535"
thm_magenta="#aa759f"
thm_pink="#ac4142"
thm_red="#ac4142"
thm_green="#90a959"
thm_yellow="#f4bf75"
thm_blue="#6a9fb5"
thm_orange="#f4bf75"
thm_black4="#151515"

# Status bar
set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"


# Statusline - other windows
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"

# Statusline - right side
set -g status-right "#[fg=${thm_cyan},bg=${thm_bg},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_bg}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[fg=${thm_cyan}]#{?client_prefix,#[fg=${thm_magenta}],}  #[fg=${thm_fg},bg=${thm_bg}] #S "

# Statusline - left side (empty)
set -g status-left ""

# Modes
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"
